grpc:
  client:
    defaults:
      threadPoolBeanName: defaultExecutor
    clients:
      default:
        target: 127.0.0.1:6565
        sslCertChainClassPath: myClient.crt
        sslPrivateKeyClassPath: myClient.key.pkcs8
        sslTrustCertCollectionClassPath: myServer.crt
        sslClientAuth: require
      client1:
        target: 127.0.0.1:6566
      client2:
        target: 127.0.0.1:6567
        threadPoolBeanName: client2Executor
      client3:
        target: 127.0.0.1:6568
      lb:
        target: lb:127.0.0.1/127.0.0.1:6666,127.0.0.1/127.0.0.1:6667
        sslCertChainClassPath: myClient.crt
        sslPrivateKeyClassPath: myClient.key.pkcs8
        sslTrustCertCollectionClassPath: myServer.crt
        sslClientAuth: require